spring:
  datasource:
    url: jdbc:mysql://stock-portfolio-db.cppifkfp3eiu.ap-northeast-2.rds.amazonaws.com:3306/testdb?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: stockyebali
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10
    open-in-view: false

server:
  shutdown: graceful

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: debug